---
- name: reload firewall
  become: true
  shell: sh -c 'iptables-restore < /etc/iptables/rules.v4 && ip6tables-restore < /etc/iptables/rules.v6'
  listen: 'reload firewall'

- name: sleep for 3 seconds and continue with play
  wait_for: timeout=3
  delegate_to: localhost
  listen: 'reload firewall'

- name: restart docker daemon
  become: true
  service:
    name: docker
    state: restarted
  ignore_errors: yes
  when: restart_docker
  listen: 'reload firewall'

- name: sleep 60 seconds
  shell: sleep 60
  when: restart_docker
  listen: 'reload firewall'
